### PR TITLE
Create EmailAddressTest, adjusting AddResearchOverviewTest and enrich

### PR DESCRIPTION
**Pull request by MichelHeon**
SampleGraphUtil with helper methods

### CODE REVIEW

**Review by awoods — CHANGES_REQUESTED** [review]
Running the vivo-regression-tests (`mvn clean install`) on a clean VIVO, I get errors on setup because there is an expectation of credentials:
https://github.com/vivo-community/vivo-regression-tests/pull/1/files#diff-819060c8ef4e931387a8bfe6b6ddcb6cL21-L22

Do you have thoughts on how to enable running the tests on a clean VIVO, or do you expect that some manual setup be required.

**Comment by MichelHeon** [comment]
In fact, you would have to change the credentials to match those of your configuration which is specified in runtimes.properties. But yes, normally the testcase should automatically load the data needed to run it.
Michel

**Comment by MichelHeon** [comment]
This commit whill help to manage execution properties

**Comment by MichelHeon** [comment]
@awoods this is a new release to merge on master

**Comment by MichelHeon** [comment]
Hi @awoods, Voici une nouvelle version à joindre à la branche master après que tu y auras les inspections nécessaires.

**Comment by awoods** [comment]
This pull-request appears to have merge conflicts that need to be resolved before a merge is possible.

**Comment by awoods** [comment]
There was a very similar pull-request that was merged into `master` earlier this week: https://github.com/vivo-community/vivo-regression-tests/pull/3
..from the same `develop` branch.

**Comment by MichelHeon** [comment]
@awoods I don't understand... I solve conflicts but the system refuses to commit. "Invalid commiter"
In fact, the conflict is easy to resolve, just overwrite the master version with the dev version.

**Comment by awoods** [comment]
I believe the problem is you have two pull-requests that have overlapping changes to the same files:
https://github.com/vivo-community/vivo-regression-tests/pull/1
https://github.com/vivo-community/vivo-regression-tests/pull/3

..actually, those two pull-requests contain some of the same commits??
https://github.com/vivo-community/vivo-regression-tests/pull/1/commits
https://github.com/vivo-community/vivo-regression-tests/pull/3/commits

I would suggest creating a new branch based on `master`, adding the commits from pull/1 that are new, then creating a new pull-request and closing pull/1.

**Comment by MichelHeon** [comment]
It's not possible to simply destroy the PRs and force the dev code to go to master.

**Comment by awoods** [comment]
@MichelHeon , I will rework your pull-request here (https://github.com/vivo-community/vivo-regression-tests/pull/1) this weekend to produce something that can be merged.

In order to work collaboratively in the VIVO community, we have established some Git community practices. When you have a chance, it may be helpful to read:
https://github.com/vivo-project/VIVO/wiki/Git---GitHub-Processes

**Comment by awoods** [comment]
@MichelHeon : The new https://github.com/vivo-community/vivo-regression-tests/pull/4 rebases https://github.com/vivo-community/vivo-regression-tests/pull/1 on the `master` branch. 

You will want to verify the functionality in this https://github.com/vivo-community/vivo-regression-tests/pull/4 ...as there were many conflicts. If the functionality is correct, we can merge https://github.com/vivo-community/vivo-regression-tests/pull/4 into `master` and close https://github.com/vivo-community/vivo-regression-tests/pull/1.

**Comment by MichelHeon** [comment]
@awoods Concerning the most recent message, the last commit of PR#4 is older than the last commit of PR#1. In fact. we can ignore PR#4 is directly merge the last commit of PR#1 into the Master branch.

**Comment by awoods** [comment]
If I understand your comment correctly, you are suggesting we merge this PR (https://github.com/vivo-community/vivo-regression-tests/pull/1) into `master`. 

As you can see, there are merge conflicts with https://github.com/vivo-community/vivo-regression-tests/pull/1 .

https://github.com/vivo-community/vivo-regression-tests/pull/4 is an attempt at resolving those merge conflicts. If you are happy that the functionality in https://github.com/vivo-community/vivo-regression-tests/pull/4 accurately captures what you are expecting with the work in https://github.com/vivo-community/vivo-regression-tests/pull/1 , we can move forward by merging https://github.com/vivo-community/vivo-regression-tests/pull/4 .

**Comment by MichelHeon** [comment]
@awoods  PR4 has long since been out of date. Indeed you understood well, you have to "overwrite" the master branch with the content of dev

**Comment by awoods** [comment]
I created https://github.com/vivo-community/vivo-regression-tests/pull/4 two days ago... it is already "long since out of date"?

Anyways, please let me know when an updated pull-request is ready for review/merge.

**Comment by awoods** [comment]
@MichelHeon : I am getting the impression that you would rather overwrite the `master` branch with your work in the `develop` branch. I will admit, doing so is generally frowned upon due to the fact that it disconnects any work that others in the community are doing on this project. It deteriorates trust in the project.
However, given the relatively small chance that anyone else is using or working on vivo-regression-tests at this point, it is probably an safe operation to perform.

Please let me know when all the changes you want to have in the `develop` branch are there, and I will clobber the `master` branch with a copy of `develop`... then I will remove `develop`.

Going forward, for each new test or incremental improvement, please make a local branch off of `master`, make your change, then submit a pull-request. Each pull-request should have a specific functional intent, with limited scope.

Please let me know if you would like to chat about standard Git/GitHub practices. Here is a brief write-up in the meantime:
https://github.com/vivo-project/VIVO/wiki/Git---GitHub-Processes

**Comment by MichelHeon** [comment]
@awoods - I agree that in this case it's a band-aid solution...I don't have any worries about creating a branch for future additions.  But in the meantime it would be necessary to merge some to master.

**Comment by awoods** [comment]
Please let me know when the `develop` branch is ready to move to `master`.

**Comment by MichelHeon** [comment]
@awoods it is ready

**Pull request merged**
