### PR TITLE
Feature 1801 regtest

### PR DESCRIPTION
**Pull request by MichelHeon**
Adaptation of the test bench to future test requirements for the development of regression tests running between VIVO 1.11.1 and VIVO i18n 1.11.2-SNAPSHOT. 

The documentation 'in progress' is available at [https://wiki.uqam.ca/display/VIVOPUB/3%29+vivo-regression-test%3A+a+Test+Bench+Tool++for+the+Continuous+Evaluation+of+VIVO%27s+Development](url)

Voir aussi : [https://jira.lyrasis.org/secure/RapidBoard.jspa?rapidView=36&projectKey=VIVO&view=planning&selectedIssue=VIVO-1885&quickFilter=75&issueLimit=100](url)

### CODE REVIEW

**Review by awoods — CHANGES_REQUESTED** [review]
Trying to build locally, I get the same error as:
https://travis-ci.com/github/awoods/vivo-regression-tests/jobs/352435183

**Comment by UQAM-VIVO** [comment]
@awoods 
The testbed has been developed under Windows, with Firefox (It is probably to be added in the readme file) and for the moment it is the target environment . For Linux, probably it is necessary to include the Silenium drivers of linux-firefox. in the pre configuration of the environment but this has not been tested, being out of UQAM-DEV was part of the scope of the project, but working in LINUX was not part of it. 
Anyway I think that the test must first be validated in the original environment and then generalize it to other ones like Linux. But it's certain we won't be able to cover all OSes (Ubuntu, CentOS, MacOS ) with all browsers (FireFos Chrome...)  for any type of widow manager in all forms of deployments (e.g. travis CI) in a reasonable amount of time....

**Comment by awoods** [comment]
After setting up the regression-testing environment based on: 
- https://wiki.uqam.ca/display/VIVOPUB/4%29+vivo-regression-test%3A+a+Test+Bench+Tool++for+the+Continuous+Evaluation+of+VIVO%27s+Development

I ran the tests against the current sprint-i18n branches. Running against the three profiles:
- ResearchOverviewToPersonTest
- EmailAddressTest
- HeadOfFacultyTest

Not all tests passed:
```
===============================================
VIVO Edit HeadOfFaculty UnitTest
Total tests run: 20, Failures: 0, Skips: 0
===============================================
```
```
===============================================
VIVO Edit emailAddress UnitTest
Total tests run: 20, Failures: 4, Skips: 8
===============================================
```
```
===============================================
VIVO Edit ResearchOverviewToPerson UnitTest
Total tests run: 20, Failures: 0, Skips: 0
===============================================
```
Are these results expected?


The full results are in the [gist](https://gist.github.com/awoods/2e3399a810467026fc01eb1e95e8b98b)

Finally, there appears to be a merge conflict in the pom.xml file.

**Comment by michel-heon** [comment]
The results are the ones expected.

Regarding the 'VIVO Edit emailAddress UnitTest' there is an error that I am correcting in another upcoming PR.
I still propose to merge the branch despite this error which will be corrected in the next PR.

**Comment by awoods** [comment]
Once you resolve the merge conflict on the pom.xml, I will merge this PR. Let me know if you need some help.

**Pull request merged**
